// Sincroniza SOLO fuentes públicas y config.example.json con el flujo distribuible.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const target=path.join(root,'workflow.configurable.json');
const workflow=JSON.parse(fs.readFileSync(target,'utf8'));
const config=JSON.parse(fs.readFileSync(path.join(root,'config.example.json'),'utf8'));
if (config.configuracionLista !== false || config.fuenteAutorizada !== false) throw new Error('La plantilla pública debe estar desactivada. Usa configure.mjs para el perfil privado.');
const node=name=>workflow.nodes.find(n=>n.name===name);
const read=name=>fs.readFileSync(path.join(root,'src',name),'utf8');
workflow.name='Job Alerts — Búsqueda de empleo para cualquier rubro';
workflow.active=false;
node('Configuración').parameters.jsCode=read('config-guard.js').replace('const config = {};','const config = '+JSON.stringify(config,null,2)+';');
node('Analizar respuesta IA').parameters.jsCode=read('analyze.js');
node('Construir CV LaTeX').parameters.jsCode=read('cv.js');
node('Evaluar con Gemini').parameters.jsonBody='={{ (() => {\n'+read('gemini-body.js')+'\n})() }}';
node('Unir resultados').parameters.jsCode=node('Unir resultados').parameters.jsCode.replace("String(datos.categoria_origen || 'qa')","String(datos.categoria_origen || '')");
fs.writeFileSync(target,JSON.stringify(workflow,null,2)+'\n');
console.log('Plantilla pública sincronizada. Ejecuta node scripts/validate.mjs antes de publicarla.');
